
name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: ubuntu-24.04
    runs-on: ubuntu-24.04
    container: ghcr.io/extremscorner/libogc2:20260719@sha256:3fcaa909bb8482c31d0721deb463a19baf1e5cdc3469cfa352249f0e88cc1983

    # Comments from original CI:
    #
    # Download devkitPPC r37, libogc 2.1.0, bin2s, elf2dol, ppc-mxml 2.11, libfat-ogc 1.1.5 and devkitppc-rules 1.1.0
    # general-tools is needed for bin2s and gamecube-tools is needed for elf2dol
    #
    # TODO - make sure this works?

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
          
    - name: Build
      run: |
        export BSLUGDIR=$(pwd)/bslug
        make && make install
        make -C modules
        make release

    - name: Upload release
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: release
        path: |
          release/